from enum import Enum

# Global configuration variables
DEVICE_NAME = "emulator-5554"
API_KEY = "your_api_key_here"
DEBUG_MODE = True
LOG_FILE = "app.log"
MAX_RAW_X = 32767
MAX_RAW_Y = 32767
SCREEN_WIDTH = 720
SCREEN_HEIGHT = 1280
KEYBOARD_DEVICE = "/dev/input/event13"
MOUSE_DEVICE = "/dev/input/event2"


class PriorityState(Enum):
    TEXT = 0
    DESCRIPTION = 1
    CLASS = 2


# Define the key mapping dictionary
KEY_MAPPING = {
    'KEY_ESC': 'ESC',
    'KEY_1': '1',
    'KEY_2': '2',
    'KEY_3': '3',
    'KEY_4': '4',
    'KEY_5': '5',
    'KEY_6': '6',
    'KEY_7': '7',
    'KEY_8': '8',
    'KEY_9': '9',
    'KEY_0': '0',
    'KEY_MINUS': '-',
    'KEY_EQUAL': '=',
    'KEY_BACKSPACE': 'BACKSPACE',
    'KEY_TAB': 'TAB',
    'KEY_Q': 'q',
    'KEY_W': 'w',
    'KEY_E': 'e',
    'KEY_R': 'r',
    'KEY_T': 't',
    'KEY_Y': 'y',
    'KEY_U': 'u',
    'KEY_I': 'i',
    'KEY_O': 'o',
    'KEY_P': 'p',
    'KEY_LEFTBRACE': '[',
    'KEY_RIGHTBRACE': ']',
    'KEY_ENTER': 'ENTER',
    'KEY_LEFTCTRL': 'LEFTCTRL',
    'KEY_A': 'a',
    'KEY_S': 's',
    'KEY_D': 'd',
    'KEY_F': 'f',
    'KEY_G': 'g',
    'KEY_H': 'h',
    'KEY_J': 'j',
    'KEY_K': 'k',
    'KEY_L': 'l',
    'KEY_SEMICOLON': ';',
    'KEY_APOSTROPHE': "'",
    'KEY_GRAVE': '`',
    'KEY_LEFTSHIFT': 'LEFTSHIFT',
    'KEY_BACKSLASH': '\\',
    'KEY_Z': 'z',
    'KEY_X': 'x',
    'KEY_C': 'c',
    'KEY_V': 'v',
    'KEY_B': 'b',
    'KEY_N': 'n',
    'KEY_M': 'm',
    'KEY_COMMA': ',',
    'KEY_DOT': '.',
    'KEY_SLASH': '/',
    'KEY_RIGHTSHIFT': 'RIGHTSHIFT',
    'KEY_KPASTERISK': '*',
    'KEY_LEFTALT': 'LEFTALT',
    'KEY_SPACE': ' ',
    'KEY_CAPSLOCK': 'CAPSLOCK',
    'KEY_F1': 'F1',
    'KEY_F2': 'F2',
    'KEY_F3': 'F3',
    'KEY_F4': 'F4',
    'KEY_F5': 'F5',
    'KEY_F6': 'F6',
    'KEY_F7': 'F7',
    'KEY_F8': 'F8',
    'KEY_F9': 'F9',
    'KEY_F10': 'F10',
    'KEY_NUMLOCK': 'NUMLOCK',
    'KEY_SCROLLLOCK': 'SCROLLLOCK',
    'KEY_KP7': '7',
    'KEY_KP8': '8',
    'KEY_KP9': '9',
    'KEY_KPMINUS': '-',
    'KEY_KP4': '4',
    'KEY_KP5': '5',
    'KEY_KP6': '6',
    'KEY_KPPLUS': '+',
    'KEY_KP1': '1',
    'KEY_KP2': '2',
    'KEY_KP3': '3',
    'KEY_KP0': '0',
    'KEY_KPDOT': '.',
    'KEY_102ND': '<',
    'KEY_F11': 'F11',
    'KEY_F12': 'F12',
    'KEY_RO': 'RO',
    'KEY_HIRAGANA': 'HIRAGANA',
    'KEY_HENKAN': 'HENKAN',
    'KEY_KPENTER': 'ENTER',
    'KEY_RIGHTCTRL': 'RIGHTCTRL',
    'KEY_KPSLASH': '/',
    'KEY_SYSRQ': 'SYSRQ',
    'KEY_RIGHTALT': 'RIGHTALT',
    'KEY_LINEFEED': '\n',
    'KEY_HOME': 'HOME',
    'KEY_UP': 'UP',
    'KEY_PAGEUP': 'PAGEUP',
    'KEY_LEFT': 'LEFT',
    'KEY_RIGHT': 'RIGHT',
    'KEY_END': 'END',
    'KEY_DOWN': 'DOWN',
    'KEY_PAGEDOWN': 'PAGEDOWN',
    'KEY_INSERT': 'INSERT',
    'KEY_DELETE': 'DELETE',
    'KEY_MUTE': 'MUTE',
    'KEY_VOLUMEDOWN': 'VOLUMEDOWN',
    'KEY_VOLUMEUP': 'VOLUMEUP',
    'KEY_POWER': 'POWER',
    'KEY_KPEQUAL': '=',
    'KEY_PAUSE': 'PAUSE',
    'KEY_KPCOMMA': ',',
    'KEY_YEN': 'YEN',
    'KEY_LEFTMETA': 'LEFTMETA',
    'KEY_RIGHTMETA': 'RIGHTMETA',
    'KEY_COMPOSE': 'COMPOSE',
    'KEY_STOP': 'STOP',
    'KEY_AGAIN': 'AGAIN',
    'KEY_PROPS': 'PROPS',
    'KEY_UNDO': 'UNDO',
    'KEY_FRONT': 'FRONT',
    'KEY_COPY': 'COPY',
    'KEY_OPEN': 'OPEN',
    'KEY_PASTE': 'PASTE',
    'KEY_FIND': 'FIND',
    'KEY_CUT': 'CUT',
    'KEY_HELP': 'HELP',
    'KEY_MENU': 'MENU',
    'KEY_CALC': 'CALC',
    'KEY_SLEEP': 'SLEEP',
    'KEY_WAKEUP': 'WAKEUP',
    'KEY_MAIL': 'MAIL',
    'KEY_BOOKMARKS': 'BOOKMARKS',
    'KEY_COMPUTER': 'COMPUTER',
    'KEY_BACK': 'BACK',
    'KEY_FORWARD': 'FORWARD',
    'KEY_NEXTSONG': 'NEXTSONG',
    'KEY_PLAYPAUSE': 'PLAYPAUSE',
    'KEY_PREVIOUSSONG': 'PREVIOUSSONG',
    'KEY_STOPCD': 'STOPCD',
    'KEY_HOMEPAGE': 'HOMEPAGE',
    'KEY_REFRESH': 'REFRESH',
    'KEY_SEARCH': 'SEARCH',
    'KEY_MEDIA': 'MEDIA',
    'KEY_KBDILLUMDOWN': 'KBDILLUMDOWN',
    'KEY_KBDILLUMUP': 'KBDILLUMUP',
    'KEY_SEND': 'SEND',
    'KEY_REPLY': 'REPLY',
    'KEY_GREEN': 'GREEN',
    'KEY_APPSELECT': 'APPSELECT',
    'KEY_SCREENSAVER': 'SCREENSAVER',
    'KEY_VOICECOMMAND': 'VOICECOMMAND',
    'KEY_ASSISTANT': 'ASSISTANT',
    'KEY_KBD_LAYOUT_NEXT': 'KBD_LAYOUT_NEXT',
    'KEY_EMOJI_PICKER': 'EMOJI_PICKER',
    # Handle keys like '01c4' and '01c5' by mapping them to their hex codes
    '01c4': 'KEY_01C4',
    '01c5': 'KEY_01C5',
    # Add any additional keys as needed
}

DEFAULT_KEY_VALUE = 'UNKNOWN_KEY'