import uiautomator2 as u2
d = u2.connect('emulator-5554')
import time
d(description='Location list').click()
time.sleep(1)
d(description='Add a new location').click()
time.sleep(1)
d(text='Search for a location…').click()
time.sleep(1)
d.send_keys("new york")
d.send_action()
time.sleep(1)
time.sleep(1)
d(text='United States, New York').click()
time.sleep(1)
d(text='Save').click()
time.sleep(1)
d(text='New York').click()
time.sleep(1)
